# Generated by Django 5.1.3 on 2024-11-28 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilo_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Iveskite markę (pvz. Ford )', max_length=100, verbose_name='Markė')),
                ('modelis', models.CharField(help_text='Iveskite modelį (pvz. Focus )', max_length=100, verbose_name='Modelis')),
            ],
            options={
                'verbose_name_plural': 'Automobilio modeliai',
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Iveskite paslaugos pavadinima (pvz.Tepalu keitimas)', max_length=100, verbose_name='Pavadinimas')),
                ('kaina', models.IntegerField(help_text='Iveskite kaina paslaugos(pvz: 199)', verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Iveskite Valstybini nr.(pvz AAA000)', max_length=15, verbose_name='Valstybinis_NR')),
                ('vin_kodas', models.CharField(help_text='Iveskite VIN (pvz.3C6UR5CJXEG146621)', max_length=17, verbose_name='VIN_Kodas')),
                ('klientas', models.CharField(help_text='Vardas Pavarde pvz(Juozas Juozaitis)', max_length=100, verbose_name='Klientas')),
                ('automobilio_modelis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilo_modelis')),
            ],
            options={
                'verbose_name_plural': 'Automobilis',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('status', models.CharField(blank=True, choices=[('Uzregistruotas', 'Uzregistruota'), ('Eileje', 'Eileje'), ('Tvarkomas', 'Tvarkoma'), ('Galima atsiimti', 'Galima atsiimti')], default='uzregistruotas', help_text='Statusas', max_length=20)),
                ('automobilis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilis')),
            ],
            options={
                'verbose_name_plural': 'Uzsakymai',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.CharField(help_text='Iveskite kieki', max_length=250, verbose_name='Kiekis')),
                ('paslauga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.paslauga')),
                ('uzsakymo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.uzsakymas')),
            ],
        ),
    ]
