# Generated by Django 5.1.3 on 2024-12-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Įveskite markę (pvz. Ford)', max_length=100, verbose_name='Markė')),
                ('modelis', models.CharField(help_text='Įveskite modelį (pvz. Focus)', max_length=100, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilio modeliai',
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugos pavadinimą (pvz. Tepalų keitimas)', max_length=100, verbose_name='Pavadinimas')),
                ('kaina', models.IntegerField(help_text='Įveskite paslaugos kainą (pvz. 199)', verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Įveskite Valstybinį nr. (pvz. AAA000)', max_length=15, verbose_name='Valstybinis NR')),
                ('vin_kodas', models.CharField(help_text='Įveskite VIN (pvz. 3C6UR5CJXEG146621)', max_length=17, verbose_name='VIN Kodas')),
                ('klientas', models.CharField(help_text='Vardas Pavardė (pvz. Juozas Juozaitis)', max_length=100, verbose_name='Klientas')),
                ('automobilio_modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilio_modelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('status', models.CharField(blank=True, choices=[('uzregistruotas', 'Užregistruota'), ('eileje', 'Eilėje'), ('tvarkomas', 'Tvarkoma'), ('galima_atsiimti', 'Galima atsiimti')], default='uzregistruotas', help_text='Statusas', max_length=20)),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilis')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.CharField(help_text='Įveskite kiekį', max_length=250, verbose_name='Kiekis')),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.paslauga')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.uzsakymas')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'Užsakymo eilutės',
            },
        ),
    ]
