# Generated by Django 5.1.3 on 2024-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='car_pic',
            field=models.ImageField(null=True, upload_to='car_pic', verbose_name='Foto'),
        ),
    ]
