# Generated by Django 5.1.3 on 2024-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_automobilis_car_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='car_pic',
            field=models.ImageField(blank=True, null=True, upload_to='car_pic', verbose_name='Foto'),
        ),
    ]
