# Generated by Django 5.1.3 on 2024-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_uzsakymas_vartotojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateField(blank=True, null=True, verbose_name='Terminas'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('uzregistruotas', 'Užregistruota'), ('eileje', 'Eilėje'), ('tvarkomas', 'Vyksta reomonto darbai'), ('galima_atsiimti', 'Galima atsiimti')], default='uzregistruotas', help_text='Statusas', max_length=20),
        ),
    ]
